import Foundation

/// Configuration for ElevenLabs conversational AI
public struct ConversationAuth: Sendable {
    /// The source of authentication for the conversation
    public enum AuthSource: Sendable {
        /// Use a public agent ID (no authentication required)
        case publicAgentId(String)
        /// Use a conversation token from your backend
        case conversationToken(String)
        /// Use a signed WebSocket URL from your backend (agent ID parsed from the URL)
        case signedWebSocketURL(url: String, agentId: String)
    }

    public let authSource: AuthSource

    /// Initialize with a public agent ID
    public static func publicAgent(id: String) -> Self {
        .init(authSource: .publicAgentId(id))
    }

    /// Initialize with a conversation token
    public static func conversationToken(_ token: String) -> Self {
        .init(authSource: .conversationToken(token))
    }

    /// Initialize with a signed WebSocket URL generated by your backend.
    /// Throws if the URL is missing the required `agent_id` query parameter.
    public static func signedWebSocketURL(_ url: String) throws -> Self {
        guard
            let agentId = URLComponents(string: url)?
            .queryItems?
            .first(where: { $0.name == "agent_id" })?
            .value,
            !agentId.isEmpty
        else {
            throw ConversationError.authenticationFailed(
                "Signed WebSocket URL is missing the agent_id query parameter."
            )
        }
        return .init(authSource: .signedWebSocketURL(url: url, agentId: agentId))
    }
}
