import Foundation

/// Configuration for ElevenLabs conversational AI
public struct ConversationCredentials: Sendable {
    /// The source of authentication for the conversation
    public enum AuthSource: Sendable {
        /// Use a public agent ID (no authentication required)
        case publicAgentId(String)
        /// Use a conversation token from your backend
        case conversationToken(String)
        /// Use a signed WebSocket URL from your backend (agent ID parsed from the URL)
        case signedWebSocketURL(url: String, agentId: String)
        /// Custom token provider for advanced use cases
        case customTokenProvider(@Sendable () async throws -> String)
    }

    public let authSource: AuthSource
    /// Optional environment for the agent (defaults to production when nil)
    public let environment: String?
    public var agentId: String {
        switch authSource {
        case let .publicAgentId(id):
            id
        case let .signedWebSocketURL(_, agentId):
            agentId
        case .conversationToken, .customTokenProvider:
            "unknown"
        }
    }

    /// Initialize with a public agent ID
    public static func publicAgent(id: String, environment: String? = nil) -> Self {
        .init(authSource: .publicAgentId(id), environment: environment)
    }

    /// Initialize with a conversation token
    public static func conversationToken(_ token: String, environment: String? = nil) -> Self {
        .init(authSource: .conversationToken(token), environment: environment)
    }

    /// Initialize with a signed WebSocket URL generated by your backend.
    /// Throws if the URL is missing the required `agent_id` query parameter.
    public static func signedWebSocketURL(_ url: String) throws -> Self {
        guard
            let agentId = URLComponents(string: url)?
            .queryItems?
            .first(where: { $0.name == "agent_id" })?
            .value,
            !agentId.isEmpty
        else {
            throw ConversationError.authenticationFailed(
                "Signed WebSocket URL is missing the agent_id query parameter."
            )
        }
        return .init(
            authSource: .signedWebSocketURL(url: url, agentId: agentId),
            environment: nil
        )
    }

    /// Initialize with a custom token provider
    public static func customTokenProvider(
        _ provider: @escaping @Sendable () async throws -> String,
        environment: String? = nil
    ) -> Self {
        .init(authSource: .customTokenProvider(provider), environment: environment)
    }
}

@available(*, deprecated, renamed: "ConversationCredentials")
public typealias ElevenLabsConfiguration = ConversationCredentials
